### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by WazirDeveloper93** [rajchandak/LanguageTranslator#1]
the app is crashed on all devices other then android 7.1.1

**Comment by WazirDeveloper93** [comment]
what is the solution for this issue and also how to add more languages

**Comment by rajchandak** [comment]
I had developed this app for a hackathon, so it hasn't been monitored since then.

The App is crashing because the Google Cloud Translate API Key I had used has expired. If you wish to test the app, enter your Google Translate API Key in the `API_KEY` string variable in `BaseFragmentClass.java`

You can add more languages to the `languages` and `languageCodes` arrays in `BaseFragmentClass.java`.
For country images, add them to `images` array in `BaseFragmentClass.java`
